### ISSUE TITLE
Koala taking food causes red error

### ISSUE THREAD

**Issue by tobyamiel** [BearlyHumans/squirrelville#99]
This error appears and duplicates infinitely(?) when Koala takes food and opens a gate. 

This is tested for the beach and forest koala, I assume it's true for the rest as well.

![image](https://user-images.githubusercontent.com/48305155/136131850-6d388c1c-2beb-4b5a-870a-f5c16e557c23.png)

**Comment by 102747419** [comment]
I remember encountering that error but I was sure I added code to fix that. 😖

**Comment by 102747419** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix error caused by NPCs deleting food from their assigned food area](https://trello.com/c/9hZcOYYf/217-fix-error-caused-by-npcs-deleting-food-from-their-assigned-food-area)
